@startuml 03x_ProvideMacTableOfAllDevices
skinparam responseMessageBelowArrow true

title PromptForProvidingAllMacTablesCausesReadingFromElasticSearch

participant "MATR://v1/provide-mac-table-of-all-devices"
participant "ElasticSearch"

[-> "MATR://v1/provide-mac-table-of-all-devices": (apiKeyAuth)

"MATR://v1/provide-mac-table-of-all-devices" -> "ElasticSearch"
"ElasticSearch" --> "MATR://v1/provide-mac-table-of-all-devices": {list-of(MountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

[<--"MATR://v1/provide-mac-table-of-all-devices": {list-of(MountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

@enduml