@startuml 04x_ProvideMacTableOfSpecificDevice
skinparam responseMessageBelowArrow true

title PromptForProvidingSpecificMacTableCausesReadingFromElasticSearch

participant "MATR://v1/provide-mac-table-of-specific-device"
participant "ElasticSearch"

[-> "MATR://v1/provide-mac-table-of-specific-device": {mount-name} (apiKeyAuth)

"MATR://v1/provide-mac-table-of-specific-device" -> "ElasticSearch": {mount-name}
"ElasticSearch" --> "MATR://v1/provide-mac-table-of-specific-device": {list-of(MountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

[<--"MATR://v1/provide-mac-table-of-specific-device": {list-of(MountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

@enduml