@startuml
skinparam responseMessageBelowArrow true

"extern" -> "/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation": {targetMacAddress}

"/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation" -> "ElasticSearch": {targetMacAddress}
"ElasticSearch" --> "/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation": {list-of(mount-name-with-an-egressLtp-that-contains-targetMacAddress, original-ltp-name)}

"/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation" --> "extern": {list-of(mount-name-with-an-egressLtp-that-contains-targetMacAddress, original-ltp-name)}

@enduml