@startuml
skinparam responseMessageBelowArrow true

"generic representation" -> "/v1/provide-list-of-network-elements-on-path-in-generic-representation": {targetMacAddress}

"/v1/provide-list-of-network-elements-on-path-in-generic-representation" -> "ElasticSearch": {targetMacAddress}
"ElasticSearch" --> "/v1/provide-list-of-network-elements-on-path-in-generic-representation": {list-of-mount-names-with-an-egressLtpUUid-equal-to-targetMacAddress}

"/v1/provide-list-of-network-elements-on-path-in-generic-representation" --> "generic representation": {list-of-mount-names-with-an-egressLtpUUid-equal-to-targetMacAddress}

@enduml