@startuml
skinparam responseMessageBelowArrow true

"extern" -> "/v1/provide-list-of-network-element-interfaces-on-path": {targetMacAddress}

"/v1/provide-list-of-network-element-interfaces-on-path" -> "ElasticSearch": {targetMacAddress}
"ElasticSearch" --> "/v1/provide-list-of-network-element-interfaces-on-path": {list-of-mount-names-with-an-egressLtp-that-contains-targetMacAddress}

"/v1/provide-list-of-network-element-interfaces-on-path" --> "extern": {list-of-mount-names-with-an-egressLtp-that-contains-targetMacAddress}

@enduml